analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal: []
  indicator: []
  post: []
cookie_consent_form:
  enabled: false
country:
  name: Nepal
  adjective: Nepali
create_goals:
  previous_next_links: false
  goals: []
  layout: goal-by-target-vertical
create_indicators:
  previous_next_links: false
  layout: indicator
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
custom_css: []
custom_js: []
data_edit_url: 'https://github.com/open-sdg-nepal/data/tree/develop/data'
data_fields:
  units: UNIT_MEASURE
  series: SERIES
date_formats:
  - type: standard
    language: en
    format: '%Y-%m-%d'
disclaimer:
  phase: ''
  message: ''
  hidden: false
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
footer_language_toggle: none
footer_menu:
  - path: 'mailto:my-email-address@example.com'
    translation_key: menu.contact_us
  - path: 'https://twitter.com/MyTwitterAccount'
    translation_key: general.twitter
  - path: 'https://facebook.com/MyFacebookAccount'
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Lorem ipsum
    content: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis
      cursus est sed dapibus.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
  - title: Nam vestibulum
    content: |
      Nam vestibulum, purus quis porttitor imperdiet, nisl sem mollis nisl, a
      interdum risus enim vitae tortor. Donec feugiat accumsan rutrum.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
frontpage_goals_grid:
  title: Our data for Sustainable Development Goal indicators
  description: >-
    Click on each goal for our Sustainable Development Goal global indicator
    data.
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: ''
  description: ''
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: true
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: false
hide_single_unit: false
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: 'https://github.com/open-sdg-nepal/data/tree/develop/indicator-config'
  translation_link: >-
    https://github.com/open-sdg-nepal/data/tree/develop/translations/[language]/[group].yml
indicator_data_form:
  enabled: false
  repository_link: ''
indicator_metadata_form:
  enabled: false
  dropdowns: []
  repository_link: ''
  translation_link: ''
  language: ''
  scopes: []
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - en
  - ne
languages_public: []
logos: []
map_layers: []
map_options:
  disaggregation_controls: false
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
  - path: /guidance
    translation_key: menu.guidance
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
metadata_edit_url: 'https://github.com/open-sdg-nepal/data/tree/develop/meta'
metadata_tabs: []
news:
  category_links: false
progress_status:
  status_heading: ''
  status_types: []
remote_data_prefix: 'https://open-sdg-nepal.github.io/data'
reporting_status:
  title: ''
  description: ''
  disaggregation_tabs: false
  status_types:
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: inprogress
      label: status.statistics_in_progress
      hide_on_goal_pages: false
    - value: notstarted
      label: status.exploring_data_sources
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/open-sdg-nepal/data'
repository_url_site: 'https://github.com/open-sdg-nepal/site'
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: 'https://github.com/open-sdg-nepal/site/tree/develop/_data'
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
validate_indicator_config: true
validate_site_config: true
x_axis_label: ''
